CREATE DATABASE IF NOT EXISTS CD_Datenbank;
USE CD_Datenbank;


CREATE TABLE IF NOT EXISTS INTERPRETEN (
    InterpretID INT AUTO_INCREMENT PRIMARY KEY,
    Interpret VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS MUSIKRICHTUNG (
    MusikrichtungID INT AUTO_INCREMENT PRIMARY KEY,
    Musikrichtung VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TITLE (
    TitleNr INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    InterpretID INT NOT NULL,
    Beurteilung VARCHAR(255) NOT NULL,
    FOREIGN KEY (InterpretID) REFERENCES INTERPRETEN(InterpretID)
);

CREATE TABLE IF NOT EXISTS CD (
    CDNr INT AUTO_INCREMENT PRIMARY KEY,
    CDName VARCHAR(255) NOT NULL,
    InterpretID INT,
    MusikrichtungID INT,
    FOREIGN KEY (InterpretID) REFERENCES INTERPRETEN(InterpretID),
    FOREIGN KEY (MusikrichtungID) REFERENCES MUSIKRICHTUNG(MusikrichtungID)
);

CREATE TABLE IF NOT EXISTS TITLE_CD (
    TitleNr INT NOT NULL,
    CDNr INT NOT NULL,
    FOREIGN KEY (TitleNr) REFERENCES TITLE(TitleNr),
    FOREIGN KEY (CDNr) REFERENCES CD(CDNr)
);
